version: "3.9"
services:
  client:
    image: nginx:alpine
    volumes:
      - ./client:/usr/share/nginx/html:ro
    ports:
      - "3000:80"

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  worker:
    build: ./worker
    depends_on:
      - rabbitmq